import Link from "next/link";

/**
 * Drop this into any AI-facing feature's UI (e.g. under a chat input) so the
 * disclosure required by chatbot-disclosure laws and the EU AI Act's Article 50
 * transparency obligation is visible at the point of use, not just buried in a
 * legal page. See src/app/(legal)/ai-disclosure/page.tsx.
 */
export function AiDisclosureNotice({ className = "" }: { className?: string }) {
	return (
		<p className={`text-xs text-zinc-500 dark:text-zinc-400 ${className}`}>
			Generated by AI — may be inaccurate. Not professional advice.{" "}
			<Link
				href="/ai-disclosure"
				className="underline underline-offset-2 hover:text-zinc-700 dark:hover:text-zinc-200"
			>
				Learn more
			</Link>
			.
		</p>
	);
}
