name: Lockfile

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lockfile:
    uses: kornsour/gh-automation/.github/workflows/lockfile-guard.yml@656f46da71566a02a641be3dcc26e07339b6e689 # lockfile-guard.yml pinned 2026-09-06
